version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "exchange-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-174ieke5r0wdi"
s3_prefix = "exchange-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
